{
  "company": {"name": "AGC Biologics", "sector": "Kontraktudvikling og -produktion af biofarmaceutiske produkter", "description": "Global CDMO med et stort produktionscampus i København."},
  "strategy": {"priorities": ["Fleksibel global cGMP-kapacitet", "Kvalitet og regulatorisk konsistens", "Bæredygtig drift"], "facts_source": "https://www.agcbio.com/facilities/copenhagen"},
  "investments": {"facts": ["Københavnsudvidelsen omfatter 18.000 m² med produktion, kvalitetskontrol, teknik og lager samt otte 2.000 L single-use bioreaktorlinjer."], "interpretations": ["Det udvidede campus skaber et konkret behov for ensartet energi-, bygnings- og strømindsigt."]},
  "operations": {"facts": ["København har mammal- og mikrobiel produktion samt procesudvikling."], "interpretations": ["Kundetidslinjer og regulatoriske krav gør driftssikkerhed og hurtig fejlidentifikation kommercielt kritisk."]},
  "facilities": {"facts": ["Københavns campus har ISO 14001, ISO 45001 og ISO 50001 samt Silver EcoVadis-rating."], "interpretations": ["Energiledelse og dokumentation er allerede en del af den lokale driftsagenda."]},
  "business_drivers": ["cGMP-kapacitet", "Kvalitet og regulatorisk compliance", "Kundetidslinjer", "Energi- og ressourceeffektivitet"],
  "commercial_triggers": [{"fact": "København er udvidet med ny single-use produktionskapacitet.", "commercial_interpretation": "Der er en aktuel anledning til at optimere driftsdata og energi på tværs af det udvidede campus.", "confidence": 94}],
  "stakeholders": [{"role": "Site operations", "priority": "Stabil leverance og høj anlægsudnyttelse", "sales_objective": "Kvalificere drifts- og energisynlighed som et forbedringsspor."}, {"role": "Engineering og facility management", "priority": "Sikker drift af udvidet campus", "sales_objective": "Få adgang til teknisk roadmap og beslutningskriterier."}, {"role": "EHS og bæredygtighed", "priority": "ISO 50001 og dokumenterbar forbedring", "sales_objective": "Koble energiindsigt til eksisterende ledelsessystemer."}],
  "schneider_opportunities": [{"title": "Gør det udvidede campus lettere at styre", "portfolio": "EcoStruxure Building Operation", "customer_outcome": "Bedre driftsindsigt og færre manuelle grænseflader", "priority": "Høj"}, {"title": "Forankr ISO 50001 i driftsdata", "portfolio": "EcoStruxure Resource Advisor og Power Monitoring Expert", "customer_outcome": "Stærkere energiledelse og mere effektiv dokumentation", "priority": "Høj"}, {"title": "Sikre strøm til kritiske processer", "portfolio": "EcoStruxure Power", "customer_outcome": "Tidligere identifikation af strøm- og kvalitetsrisici", "priority": "Mellem"}],
  "risks": ["Produktions- og kvalitetskrav kan udsætte tekniske initiativer", "Flere funktioner skal se samme forretningsværdi før et projekt prioriteres"],
  "meeting_context": {"recommended_motion": "Workshop om drifts- og energiindsigt på Københavns campus", "investment_horizon": "0–12 måneder", "reading_time": "4 min."}
}
