{
  "company": {"name": "Bavarian Nordic", "sector": "Vacciner", "description": "International vaccinevirksomhed med forskning, udvikling og produktion af livreddende vacciner."},
  "strategy": {"priorities": ["Fortsat vækst i Travel Health", "Global lancering af chikungunya-vaccine", "Prioriteret life-cycle management af den kommercielle portefølje"], "facts_source": "https://www.bavarian-nordic.com/investor/news/news.aspx?news=7455"},
  "investments": {"facts": ["Strategisk partnerskab med Serum Institute of India udvidet med kontraktproduktion og teknologioverførsel for chikungunya-vaccine."], "interpretations": ["Kapacitets- og kvalitetsstandarder bliver vigtige, når produktionsnetværket skaleres."]},
  "operations": {"facts": ["Virksomheden fokuserer på forskning, udvikling og fremstilling af vacciner."], "interpretations": ["Driftskontinuitet og reproducerbare processer er centrale for værdiskabelsen."]},
  "facilities": {"facts": ["Virksomheden opererer i en reguleret vaccineforretning med behov for robust fremstilling."], "interpretations": ["Energidata, strømrobusthed og bygningsdrift bør kobles til produktionens risikobillede."]},
  "business_drivers": ["Skalerbar produktionskapacitet", "Regulatorisk kvalitet", "Sikker forsyning", "Kontrollerede energiomkostninger"],
  "commercial_triggers": [{"fact": "Travel Health skal fortsat vokse, og chikungunya-vaccinen lanceres globalt.", "commercial_interpretation": "Vækst og global skalering øger værdien af ensartede drifts- og energistandarder.", "confidence": 91}],
  "stakeholders": [{"role": "Produktions- og driftsledelse", "priority": "Stabil kvalitet, kapacitet og oppetid", "sales_objective": "Skabe adgang til en dialog om driftsrisiko og kommende kapacitetsbehov."}, {"role": "Teknik og facility management", "priority": "Robust og energieffektiv infrastruktur", "sales_objective": "Kvalificere en prioriteret facilitet til fælles afdækning."}, {"role": "Bæredygtighedsansvarlig", "priority": "Målbar energi- og klimaindsats", "sales_objective": "Etablere en fælles baseline for energi og rapportering."}],
  "schneider_opportunities": [{"title": "Gør næste kapacitetsløft til en fælles standard", "portfolio": "EcoStruxure Building Operation og integreret strømstyring", "customer_outcome": "Mindre projektrisiko og hurtigere stabil drift", "priority": "Høj"}, {"title": "Gør energi til en ledelsesbeslutning", "portfolio": "EcoStruxure Resource Advisor og Power Monitoring Expert", "customer_outcome": "Lavere energispild og dokumenterbar fremdrift", "priority": "Høj"}, {"title": "Beskyt kritisk vaccineproduktion", "portfolio": "EcoStruxure Power og prædiktive services", "customer_outcome": "Færre driftsafbrydelser og bedre beskyttelse af output", "priority": "Mellem"}],
  "risks": ["Forsinket adgang til projekter efter tekniske standarder er valgt", "Manglende fælles ejerkreds på tværs af drift, teknik og bæredygtighed"],
  "meeting_context": {"recommended_motion": "Strategisk afdækning på en prioriteret facilitet", "investment_horizon": "6–18 måneder", "reading_time": "4 min."}
}
